/* Create the tables for a A-|o-----o|-B relationship. */

-- Table A: Each row in A is related to zero or one row in B.
CREATE TABLE a (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    b  INT UNIQUE,  -- the foreign key to B, see later <-- can be NULL.
    x  CHAR(3)  -- example for other attributes
);

-- Table B: Each row in B is related to zero or one row in A.
CREATE TABLE b (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    y  CHAR(2)  -- example for other attributes
);

-- To table A, we add the foreign key reference constraint to table B.
ALTER TABLE a ADD CONSTRAINT a_b_fk FOREIGN KEY (b) REFERENCES b (id);
