/* Create the tables for an A-|o-----o|-B relationship. */

-- Table A: Each row in A is related to zero or one row in B.
CREATE TABLE a (
    aid   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fkbid INT UNIQUE,  -- foreign key to B, see later <-- can be NULL.
    x     CHAR(3)  -- example of other attributes
);

-- Table B: Each row in B is related to zero or one row in A.
CREATE TABLE b (
    bid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    y   CHAR(2)  -- example of other attributes
);

-- To table A, we add the foreign key reference constraint to table B.
ALTER TABLE a ADD CONSTRAINT a_fkbid_fk FOREIGN KEY (fkbid)
    REFERENCES b (bid);
