/* Create the tables for a C-|o-----||-D relationship. */

-- Table C: Each row in C is related to exactly one row in D.
CREATE TABLE c (
    cid   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fkdid INT NOT NULL UNIQUE,  -- the foreign key to D, see later
    x   CHAR(3)  -- example of other attributes
);

-- Table D: Each row in D is related to zero or one row in C.
CREATE TABLE d (
    did INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    y   CHAR(2)  -- example of other attributes
);

-- To table C, we add the foreign key reference constraint to table D.
ALTER TABLE c ADD CONSTRAINT c_fkdid_fk FOREIGN KEY (fkdid)
    REFERENCES d (did);
