/* Create the tables for a E-|o-----o<-F relationship. */

-- Table E: Each row in E is related to zero or one or many rows in F.
CREATE TABLE e (
    eid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    x   CHAR(3)  -- example of other attributes
);

-- Table F: Each row in F is related to zero or one row in E.
CREATE TABLE f (
    fid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    y   CHAR(2)  -- example of other attributes
);

-- The table for managing the relationship between E and F.
CREATE TABLE relate_e_and_f (
    fkeid INT NOT NULL                    REFERENCES e (eid),
    fkfid INT NOT NULL UNIQUE PRIMARY KEY REFERENCES f (fid)
);
