/* Create the tables for a E-|o-----o<-F relationship. */

-- Table E: Each row in E is related to zero or one or many rows in F.
CREATE TABLE e (
    eid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    x   CHAR(3)  -- example of other attributes
);

-- Table F: Each row in F is related to zero or one row in E.
CREATE TABLE f (
    fid   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fkeid INT REFERENCES e (eid),  -- the foreign key to E, can be NULL.
    y     CHAR(2)  -- example of other attributes
);
