/* Create the tables for a G-|o-----|<-H relationship. */

-- Table G: Each row in G is related to one or multiple rows in H.
CREATE TABLE g (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    h  INT NOT NULL,  -- later used to reference relate_g_and_h
    x  CHAR(3)        -- example for other attributes
);

-- Table H: Each row in H is related to zero or one row in G.
CREATE TABLE h (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    y  CHAR(2)  -- example for other attributes
);

-- The table for managing the relationship between G and H.
CREATE TABLE relate_g_and_h (
    g INT NOT NULL        REFERENCES g (id),
    h INT NOT NULL UNIQUE REFERENCES h (id),
    PRIMARY KEY (g, h)  -- Important: Primary key includes both columns.
);

-- To table G, we add the foreign key reference constraint towards
-- table relate_g_and_h. This enforces that one relation must exist.
ALTER TABLE g ADD CONSTRAINT g_id_h_fk FOREIGN KEY (id, h)
    REFERENCES relate_g_and_h (g, h);
