/* Create the tables for a G-|o-----|<-H relationship. */

-- Table G: Each row in G is related to one or multiple rows in H.
-- We force that that row in H is also related to our row in G via
-- a foreign key constraint g_h_fk.
CREATE TABLE g (
    gid   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fkhid INT NOT NULL UNIQUE,  -- row is related >= 1 H.
    x     CHAR(3)               -- example of other attributes
);

-- Table H: Each row in H is related to zero or one rows in G.
CREATE TABLE h (
    hid   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fkgid INT REFERENCES g (gid),  -- can be related to 0 or 1 G
    y     CHAR(2),                 -- example of attributes
    UNIQUE (hid, fkgid)            -- needed for g_fkhid_gid_fk
);

-- To table G, we add the foreign key reference constraint towards H.
ALTER TABLE g ADD CONSTRAINT g_fkhid_gid_fk FOREIGN KEY (fkhid, gid)
    REFERENCES h (hid, fkgid)
