/* Create the tables for a G-|o-----|<-H relationship. */

-- Table H: Each row in H is related to zero or one rows in G.
CREATE TABLE h (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    g  INT,     -- Each row related to 0 or 1 G (constraint at bottom).
    y  CHAR(2), -- example for other attributes
    CONSTRAINT h_id_g_uq UNIQUE (id, g)  -- Needed for use in fk in g.
);

-- Table G: Each row in G is related to one or multiple rows in H.
-- We force that that row in H is also related to our row in G via
-- a foreign key constraint g_h_fk.
CREATE TABLE g (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    h  INT NOT NULL UNIQUE REFERENCES h (id),  -- row is related >= 1 H.
    x  CHAR(3),    -- example for other attributes
    CONSTRAINT g_h_fk FOREIGN KEY (h, id) REFERENCES h (id, g)
);

-- To table H, we add the foreign key reference constraint towards g.
ALTER TABLE h ADD CONSTRAINT h_g_fk FOREIGN KEY (g) REFERENCES g (id);
