/* Create the table for a I-||-----||-J relationship. */

-- Table I_J: Each row holds one entity of type I and one of type J.
CREATE TABLE i_j (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    x  CHAR(3),  -- example for other attributes of entity type I
    y  CHAR(2)   -- example for other attributes of entity type J
);
