/* Create the tables for a K-||-----o<-L relationship. */

-- Table K: Each row in K is related to zero or one or many rows in L.
CREATE TABLE k (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    x  CHAR(3)  -- example for other attributes
);

-- Table L: Each row in L is related to exactly one row in K.
CREATE TABLE l (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    k  INT NOT NULL REFERENCES k (id),  -- the foreign key to K.
    y  CHAR(2)  -- example for other attributes
);
