/* Create the tables for a M-||-----|<-N relationship. */

-- The sequence for the IDs.
CREATE SEQUENCE m_id AS INT;

-- Table M: Each row in M is related to one or multiple rows in N.
CREATE TABLE m (
    id INT DEFAULT NEXTVAL('m_id') PRIMARY KEY,  -- Use ID sequence!
    n  INT NOT NULL UNIQUE,  -- Each N can only occur once.
    x  CHAR(3)               -- example for other attributes
);

-- Table N: Each row in N is related exactly one row in M.
CREATE TABLE n (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    m  INT NOT NULL REFERENCES m (id),
    y  CHAR(2) -- example for other attributes
);

-- To table M, we add the foreign key reference constraint towards
-- table n. This enforces the mandatory-many part of the relationship.
ALTER TABLE m ADD CONSTRAINT m_n_fk FOREIGN KEY (n) REFERENCES n (id);
