/* Create the tables for a M-||-----|<-N relationship. */

-- The sequence for the IDs.
CREATE SEQUENCE sqmid AS INT;

-- Table M: Each row in M is related to one or multiple rows in N.
CREATE TABLE m (
    mid   INT DEFAULT NEXTVAL('sqmid') PRIMARY KEY,  -- Use ID sequence!
    fknid INT NOT NULL UNIQUE,  -- UNIQUE: Each N is related to one M.
    x     CHAR(3)               -- example of other attributes
);

-- Table N: Each row in N is related exactly one row in M.
CREATE TABLE n (
    nid   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fkmid INT NOT NULL REFERENCES m (mid),
    y     CHAR(2),       -- example of other attributes
    UNIQUE (nid, fkmid)  -- needed for m_mid_fknid_fk
);

-- To table M, we add the foreign key reference constraint towards
-- table N. This enforces the mandatory-many part of the relationship.
ALTER TABLE m ADD CONSTRAINT m_mid_fknid_fk FOREIGN KEY (mid, fknid)
    REFERENCES n (fkmid, nid);
