/* Create the tables for an O->o-----o<-P relationship. */

-- Table O: Each row in O is related to zero or one or many rows in P.
CREATE TABLE o (
    oid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    x   CHAR(3)  -- example of other attributes
);

-- Table P: Each row in P is related to zero or one or many rows in O.
CREATE TABLE p (
    pid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    y   CHAR(2)  -- example of other attributes
);

-- The table for managing the relationship between O and P.
CREATE TABLE relate_o_and_p (
    fkoid INT NOT NULL REFERENCES o (oid),
    fkpid INT NOT NULL REFERENCES p (pid),
    PRIMARY KEY (fkoid, fkpid)  -- Primary key includes both columns.
);
