-- object: public.address | type: TABLE --
-- DROP TABLE IF EXISTS public.address CASCADE;
CREATE TABLE public.address (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	address varchar(255) NOT NULL,
	CONSTRAINT address_id_pk PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.address OWNER TO postgres;
-- ddl-end --

