/* We create the new table 'product' in our factory database. */

-- Delete the table 'product' if it exists in database 'factory'.
-- This allows you to run the example several times without error.
DROP TABLE IF EXISTS product;

-- List all tables of the user 'boss' in database 'factory'
-- There are no tables yet.
SELECT tablename FROM pg_catalog.pg_tables
    WHERE tableowner='boss';

-- The table 'product' stores all the produces that we can produce.
-- Each row of this table identifies one such product.
CREATE TABLE product (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,  -- must exist, must be unique
    price DECIMAL(10, 2) NOT NULL,  -- price (RMB): 10 digits, 2 after .
    weight INT NOT NULL,  -- the weight of the product, in grams
    width INT NOT NULL,  -- the width of the product, in mm
    height INT NOT NULL,  -- the height of the product, in mm
    depth INT NOT NULL  -- the depth of the product, in mm
);

-- List all tables of the user 'boss' in database 'factory'
-- Now we see the table 'product'.
SELECT tablename FROM pg_catalog.pg_tables
    WHERE tableowner='boss';
