/* We create the new table 'customer' in our factory database. */

-- Delete the table 'customer' if it exists in database 'factory'.
-- This allows you to run the example several times without error.
DROP TABLE IF EXISTS customer;

-- List all tables of the user 'factory_boss' in database 'factory'
-- There is only the table 'product'.
SELECT tablename FROM pg_catalog.pg_tables
    WHERE tableowner='factory_boss';

-- The table 'customer' stores all the customers that we have.
-- Each row of this table identifies one such a customer.
CREATE TABLE customer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,  -- must exist, must be unique
    mobile CHAR(20) NOT NULL UNIQUE,  -- the mobile phone number
    address VARCHAR(255) NOT NULL  -- the address
);

-- List all tables of the user 'factory_boss' in database 'customer'
-- Now we see the table 'customer'.
SELECT tablename FROM pg_catalog.pg_tables
    WHERE tableowner='factory_boss';
