-- object: public.professor | type: TABLE --
-- DROP TABLE IF EXISTS public.professor CASCADE;
CREATE TABLE public.professor (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	name varchar(255) NOT NULL,
	CONSTRAINT professor_id_pl PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.professor OWNER TO postgres;
-- ddl-end --

