-- object: public.course | type: TABLE --
-- DROP TABLE IF EXISTS public.course CASCADE;
CREATE TABLE public.course (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	professor integer NOT NULL,
	module integer NOT NULL,
	semester integer NOT NULL,
	CONSTRAINT course_id_pk PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.course OWNER TO postgres;
-- ddl-end --

