-- object: public.name | type: TABLE --
-- DROP TABLE IF EXISTS public.name CASCADE;
CREATE TABLE public.name (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	person integer NOT NULL,
	full_name varchar(255) NOT NULL,
	salutation varchar(255),
	is_official boolean NOT NULL DEFAULT True,
	start_date date NOT NULL DEFAULT CURRENT_DATE,
	end_date date,
	CONSTRAINT name_id_pk PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.name OWNER TO postgres;
-- ddl-end --

