-- object: public.address | type: TABLE --
-- DROP TABLE IF EXISTS public.address CASCADE;
CREATE TABLE public.address (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	person integer NOT NULL,
	country char(2) NOT NULL DEFAULT 'CN',
	province char(2) DEFAULT 'AH',
	city varchar(255) NOT NULL,
	district varchar(255),
	postal_code varchar(32) NOT NULL,
	street_address varchar(255) NOT NULL,
	CONSTRAINT address_id_pk PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.address OWNER TO postgres;
-- ddl-end --

