-- object: public.has_id | type: TABLE --
-- DROP TABLE IF EXISTS public.has_id CASCADE;
CREATE TABLE public.has_id (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	id_type integer NOT NULL,
	person integer NOT NULL,
	value varchar(100) NOT NULL,
	valid_from date NOT NULL,
	valid_to date,
	CONSTRAINT has_id_id_pk PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.has_id OWNER TO postgres;
-- ddl-end --

