CREATE TABLE food (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100)   NOT NULL UNIQUE,
    is_vegetarian BOOLEAN        NOT NULL,
    price         DECIMAL(10, 2) NOT NULL,
    CONSTRAINT price_ok CHECK (price > 0)
);
