/* We create the new table 'customer' in our factory database. */

-- The table 'customer' stores all the customers that we have.
-- Each row of this table identifies one such a customer.
CREATE TABLE customer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,  -- must exist
    phone VARCHAR(11) NOT NULL UNIQUE,  -- the phone number
    address VARCHAR(255) NOT NULL,  -- the address
    CONSTRAINT customer_name_ok CHECK (name ~ '^\w.*\w$'),
    CONSTRAINT customer_phone_ok CHECK (phone ~ '^\d{10,11}$')
);

-- List all tables of the user 'boss' in database 'customer'
-- Now we see the table 'customer'.
SELECT tablename FROM pg_catalog.pg_tables
    WHERE tableowner='boss';
