/* We create the new table 'demand' in our factory database. */

-- List all tables of the user 'boss' in database 'factory'
-- There are two tables: 'customer' and 'product'.
SELECT tablename FROM pg_catalog.pg_tables
    WHERE tableowner='boss';

-- The table 'demand' stores all the customer orders.
CREATE TABLE demand (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer INT NOT NULL REFERENCES customer(id),
    product INT NOT NULL REFERENCES product(id),
    amount INT NOT NULL,
    ordered DATE NOT NULL
);

-- List all tables of the user 'boss' in database 'factory'
-- Now we see the table 'demand'.
SELECT tablename FROM pg_catalog.pg_tables
    WHERE tableowner='boss';
