-- object: public.student | type: TABLE --
-- DROP TABLE IF EXISTS public.student CASCADE;
CREATE TABLE public.student (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	name varchar(255) NOT NULL,
	address_1 integer NOT NULL,
	address_2 integer,
	CONSTRAINT student_id_pk PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.student OWNER TO postgres;
-- ddl-end --

