-- The pilot table of the airline example.
CREATE TABLE pilot (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)  NOT NULL,
    flight_hours  INT           NOT NULL,
    qualification VARCHAR(30)   NOT NULL,
    date_of_birth DATE          NOT NULL,
    CONSTRAINT flight_hours_ok  CHECK (flight_hours > 100),
);
