-- Create the flight date table of the airline example.
CREATE TABLE flight_date (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight     VARCHAR(8)  NOT NULL REFERENCES flight   (flight_number),
    pilot      INT         NOT NULL REFERENCES pilot    (id),
    airplane   VARCHAR(10) NOT NULL REFERENCES airplane (tail_number),
    start_date DATE        NOT NULL);
