-- Create the booking table of the airline example.
CREATE TABLE booking (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_date INT           NOT NULL REFERENCES flight_date (id),
    passenger   INT           NOT NULL REFERENCES passenger   (id),
    class       INT           NOT NULL,
    price       DECIMAL(8, 2) NOT NULL
);
