-- Create the passenger table of the airline example.
CREATE TABLE passenger (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    date_of_birth DATE         NOT NULL,
    address       VARCHAR(255) NOT NULL);
