-- Create the passenger table of the airline example.
CREATE TABLE passenger (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255),
    date_of_birth DATE
    address       VARCHAR(255),
);
