-- The pilot table of the airline example.
CREATE TABLE pilot (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255),
    flight_hours  INT,
    qualification VARCHAR(30),
    date_of_birth DATE
);
